### PR TITLE
Add User registration form, fixes #15.

### LINKED ISSUE #15: Add register/create user functionality
Functionality: Creating a new user from the UI

A new user should be able to register a new account for her current wallet address from the UI. 

Configuration instructions should recommend using existing addresses with ETH in the test network as the ones ganache initialize. See also #8

### PR DESCRIPTION
**Pull request by atfornes**
It adds a simple user registration form when the user is not registered

### CODE REVIEW

**Comment by kuzdogan** [comment]
Thanks for the PR Antonio! There are some things missing such as adding `firstName` and `lastName` or assigning the address as `_id` when adding to the DB. 

If you can give me the access rights to the PR branch I can add the changes and complete the PR. Just checkmark **Allow edits from maintainers** here in the right sidebar.
Or I can point out what is missing in comments.

**Comment by atfornes** [comment]
Sure, thanks for reviewing!

Please share the comments in the review and I can solve the remaining issues. 

I cannot find were to give you permissions to edit

**Comment by atfornes** [comment]
I gave you write permissions at our repo. You should be able to commit changes yourself if you want. :smiley:

**Comment by kuzdogan** [comment]
I've added the necessary minor changes. Looks good!

**Comment by atfornes** [comment]
Thanks @kuzdogan! I am happy to see the quick merge :)

**Pull request merged**
