### PR TITLE
Client env port

### PR DESCRIPTION
**Pull request by atfornes**
Fix client code to be able to connect to a server port set by env variable.

### CODE REVIEW

**Comment by kuzdogan** [comment]
I think it should be named differently. I first thought you mean the frontend app's port from REACT_APP_PORT. Maybe something like SERVER_PORT or BACKEND_PORT.

**Comment by atfornes** [comment]
REACT_APP is a prefix for all the environment variables that the client can receive. We can name it REACT_APP_SERVER_PORT if you want

**Comment by kuzdogan** [comment]
That would be more clear 👍

**Comment by atfornes** [comment]
@kuzdogan , check the pull request now, I have changed the name of the environment varaible as you suggested.

**Pull request merged**
